// <auto-generated />
using System;
using InnoGotchiGame.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoGotchiGame.Web.Migrations
{
    [DbContext(typeof(InnoGotchiGameContext))]
    partial class InnoGotchiGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.ColaborationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RequestReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("RequestSenderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestReceiverId");

                    b.HasIndex("RequestSenderId");

                    b.ToTable("ColaborationRequests");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.PetFarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("PetFarms");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnPetFarmId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PictureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PictureId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.ColaborationRequest", b =>
                {
                    b.HasOne("InnoGotchiGame.Persistence.Models.User", "RequestReceiver")
                        .WithMany("AcceptedColaborations")
                        .HasForeignKey("RequestReceiverId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("InnoGotchiGame.Persistence.Models.User", "RequestSender")
                        .WithMany("SentColaborations")
                        .HasForeignKey("RequestSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestReceiver");

                    b.Navigation("RequestSender");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.Pet", b =>
                {
                    b.HasOne("InnoGotchiGame.Persistence.Models.PetFarm", "Farm")
                        .WithMany("Pets")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InnoGotchiGame.Persistence.Models.PetStatistic", "Statistic", b1 =>
                        {
                            b1.Property<int>("PetId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("BornDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DateLastDrink")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DateLastFeed")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("DeadDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("DrinkingCount")
                                .HasColumnType("int");

                            b1.Property<int>("FeedingCount")
                                .HasColumnType("int");

                            b1.Property<DateTime>("FirstHappinessDay")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("PetId");

                            b1.HasIndex("Name")
                                .IsUnique();

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsOne("InnoGotchiGame.Persistence.Models.PetView", "View", b1 =>
                        {
                            b1.Property<int>("PetId")
                                .HasColumnType("int");

                            b1.Property<int?>("PictureId")
                                .HasColumnType("int");

                            b1.HasKey("PetId");

                            b1.HasIndex("PictureId");

                            b1.ToTable("Pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");

                            b1.HasOne("InnoGotchiGame.Persistence.Models.Picture", "Picture")
                                .WithMany()
                                .HasForeignKey("PictureId")
                                .OnDelete(DeleteBehavior.SetNull);

                            b1.Navigation("Picture");
                        });

                    b.Navigation("Farm");

                    b.Navigation("Statistic")
                        .IsRequired();

                    b.Navigation("View")
                        .IsRequired();
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.PetFarm", b =>
                {
                    b.HasOne("InnoGotchiGame.Persistence.Models.User", "Owner")
                        .WithOne("OwnPetFarm")
                        .HasForeignKey("InnoGotchiGame.Persistence.Models.PetFarm", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.User", b =>
                {
                    b.HasOne("InnoGotchiGame.Persistence.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.PetFarm", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("InnoGotchiGame.Persistence.Models.User", b =>
                {
                    b.Navigation("AcceptedColaborations");

                    b.Navigation("OwnPetFarm");

                    b.Navigation("SentColaborations");
                });
#pragma warning restore 612, 618
        }
    }
}
